---
title: "California Car Crashes in 2019"
format: dashboard
server: shiny
---

```{r}
#| context: setup

# ==================================================================
# packages
# (you can use other packages if you want to)
# ==================================================================
library(tidyverse)     # ecosystem of data science packages
library(leaflet)       # web interactive maps
library(sf)            # "simple features" (vector data for maps)
library(plotly)        # web interactive plots
library(ggiraph)       # make ggplots into interactive plots
library(RColorBrewer)  # optional: nice color schemes


# ==================================================================
# import crash data, and mutate auxiliary columns for your analysis
# ==================================================================
dat<- read_csv("crashes_geospatial_2019.csv")


severity_levels <- c(
  "minor injury",
  "possible injury",
  "severe injury",
  "fatal injury"
)

dat <- dat |>
  mutate(
    COLLISION_SEVERITY = factor(COLLISION_SEVERITY, levels = severity_levels, ordered = TRUE),
      COUNTY = str_extract(LOCATION, "(?<=, ).*"),
      WDAY = wday(DATETIME, label = TRUE, abbr = FALSE))


```


# {.sidebar width="300px"}

```{r}
# input to select county
selectInput(
  inputId = "county",
  label = "Selected County",
  choices = unique(dat$COUNTY),
  selected = "ALAMEDA"
)
```

```{r}
# input to select violation (PCF_VIOL_CATEGORY)
selectInput(
  inputId = "violation",
  label = "Violation Category",
  choices = unique(dat$PCF_VIOL_CATEGORY),
  selected = "DUI"
)
```

```{r}
selectInput(
  inputId = "wday",
  label = "Filter by Day of Week:",
  choices = unique(dat$WDAY),
  selected = "MONDAY"
)
```

```{r}
# input to choose type of collision (TYPE_OF_COLLISION)
checkboxGroupInput(
  inputId = "collision",
  label = "Type of Collision",
  choices = unique(dat$TYPE_OF_COLLISION),
  selected = unique(dat$TYPE_OF_COLLISION)
)

```

```{r}
# input to decide whether to color code by severity (COLLISION_SEVERITY)
radioButtons(
  inputId = "severity",
  label = "Color by severity?",
  choices = c("yes", "no"),
  selected = "yes"
)

```

```{r}
# input to choose date range
dateRangeInput(
  inputId = "date",
  label = "Range of Dates",
  start = "2019-01-01",
  end = "2019-12-31",
  min = min(dat$DATETIME),
  max = max(dat$DATETIME)
)
```

```{r}
# input to change leaflet provider tiles
selectInput(
  inputId = "provider",
  label = "Select tile provider:",
  choices = c(
    "CartoDB.Positron",
    "CartoDB.DarkMatter",
    "Esri.WorldTerrain",
    "MtbMap",
    "Stadia.StamenWatercolor",
    "USGS.USImageryTopo"), 
  selected = "CartoDB.Positron")
```


# Tab 1

## Row

```{r}
# output: leaflet map
leafletOutput(outputId = "map")
```
# Tab 2

## Row

```{r}
# output(s) for tab-2
plotlyOutput(outputId = "plot")
```


```{r}
#| context: server

# assemble leaflet map of crash locations (tab 1)
output$map <- renderLeaflet({

  filtered <- dat |>
    filter(
      DATETIME >= input$date[1],
      DATETIME <= input$date[2],
      COUNTY == input$county,
      PCF_VIOL_CATEGORY == input$violation,
      TYPE_OF_COLLISION %in% input$collision
    )

  req(nrow(filtered) > 0)  # prevent blank rendering

  leafmap <- leaflet(filtered) |>
    addProviderTiles(input$provider)

  if (input$severity == "yes") 
    {
   pal <- colorFactor(
   palette = "Reds",   
   levels = levels(filtered$COLLISION_SEVERITY),
   ordered = TRUE
   )
    
    leafmap |>
      addCircles(
        lng = ~POINT_X,
        lat = ~POINT_Y,
        label = ~paste0("Case ID:", CASE_ID, ", ", PCF_VIOL_CATEGORY, ", Alcohol Involved: ", ALCOHOL_INVOLVED),
        color = ~pal(COLLISION_SEVERITY),
        weight = 2
      ) |>
      addLegend(
        position = "bottomright",
        pal = pal,
        values = ~COLLISION_SEVERITY,
        title = "Severity"
      )

  } 
  else {

    leafmap |>
      addCircles(
        lng = ~POINT_X,
        lat = ~POINT_Y,
        label = ~paste0(CASE_ID, ", ", PCF_VIOL_CATEGORY, ", ", ALCOHOL_INVOLVED),
        weight = 2
      )
  }
})

# assemble graphic for tab 2
output$plot <- renderPlotly({
  filtered2 <- dat |>
    filter((WDAY == input$wday), 
      DATETIME >= input$date[1],
      DATETIME <= input$date[2],
      COUNTY == input$county,
      PCF_VIOL_CATEGORY == input$violation,
      TYPE_OF_COLLISION %in% input$collision) |>
        group_by(TYPE_OF_COLLISION) |>
           summarize(count = n())
g <- filtered2 |> ggplot(aes(y = count, x = TYPE_OF_COLLISION)) +
  geom_col() +
  labs(
    title = "Number and Type of Crashes by Day of Week", 
          x = "Type of Collision", 
          y = "Number of Crashes")
  ggplotly(g)

})
```

