project:
  type: website

website:
  favicon: assets/favicon_io/favicon.ico
  title: "Project 6"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - analysis1.qmd
      - analysis2.qmd
      - about.qmd

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



