---
title: yippee
author: erin yang
format:
    revealjs:
        code-folding: true
        echo: true
        embed-resources: True
        transition: slide
        background-transition: fade
---

``` {r}
library(tidyverse)
ev <- read.csv('/Users/eriny/Documents/GitHub/stat-133/labs/lab 5/data/ev-sales-cleaned.csv')
head(ev)
```

# electric vehicle stats

## counties with most and least evs

```{r}
ev |> 
    group_by(county) |>
    summarise(sum_evs = sum(sales[fuel_type == 'Electric'], na.rm = TRUE)) |>
    arrange(desc(sum_evs))
```

The county w the most evs is: Los Angeles!

```{r}
ev |> 
    group_by(county) |>
    summarise(sum_evs = sum(sales[fuel_type == 'Electric'], na.rm = TRUE)) |>
    arrange(sum_evs)
```

the county w the least evs is: Modoc

## most and least popular evs {background-color='#afeeee'}

```{r}
ev |> filter(fuel_type == 'Electric') |>
    group_by(model) |>
    summarise(sum_models = sum(sales[fuel_type == 'Electric'], na.rm = TRUE)) |>
    arrange(desc(sum_models))
```

The most popular model is the Model Y!

```{r}
ev |> filter(fuel_type == 'Electric') |>
    group_by(model) |>
    summarise(sum_models = sum(sales[fuel_type == 'Electric'], na.rm = TRUE)) |>
    arrange(sum_models)
```

The least popular model is the SQ8 e-tron w only 5 cars