---
title: "Title of your dashboard"
format: dashboard
server: shiny
---

```{r}
#| context: setup

# ==================================================================
# packages
# (you can use other packages if you want to)
# ==================================================================
library(tidyverse)     # ecosystem of data science packages
library(leaflet)       # web interactive maps
library(sf)            # "simple features" (vector data for maps)
library(plotly)        # web interactive plots
library(ggiraph)       # make ggplots into interactive plots
library(RColorBrewer)  # optional: nice color schemes


# ==================================================================
# import crash data, and mutate auxiliary columns for your analysis
# ==================================================================

```

```{r}

crashes <- read_csv("crashes_geospatial_2019.csv") |>
  mutate(
    DATETIME = as.Date(DATETIME),
    WDAY = weekdays(DATETIME),
    COUNTY = stringr::str_trim(stringr::word(LOCATION, -1, sep = fixed(",")))
  )
```

# {.sidebar width="300px"}



```{r}
# input to select county
selectInput(
  inputId = 'county',
  label = 'County',
  choices = sort(unique(crashes$COUNTY)),
  selected = 'Alameda'
)
```

```{r}
# input to select violation (PCF_VIOL_CATEGORY)
selectInput(
  inputId = 'violation',
  label = 'Violation',
  choices = sort(unique(crashes$PCF_VIOL_CATEGORY)),
  selected = 'DUI'
)
```

```{r}
# input to choose type of collision (TYPE_OF_COLLISION)
checkboxGroupInput(
  inputId = 'coltype',
  label = 'Type of Collision',
  choices = sort(unique(crashes$TYPE_OF_COLLISION)),
  selected = sort(unique(crashes$TYPE_OF_COLLISION))
)
```

```{r}
# input to decide whether to color code by severity (COLLISION_SEVERITY)
radioButtons(
  inputId = 'color',
  label = 'Color by Severity?',
  choices = c('yes', 'no'),
  selected = 'yes'
)
```

```{r}
# input to choose date range
dateRangeInput(
  inputId = 'dates',
  label = 'Date Range',
  start = as.Date("2019-01-01"),
  end = as.Date("2019-12-31")
)
```

```{r}
# input to change leaflet provider tiles
selectInput(
  inputId = "provider",
  label = "Select tile provider:",
  choices = c(
    "CartoDB.Positron",
    "CartoDB.DarkMatter",
    "Esri.WorldTerrain",
    "MtbMap",
    "Stadia.StamenWatercolor",
    "USGS.USImageryTopo"), 
  selected = "CartoDB.Positron")
```

```{r}
selectInput(
  inputId = "wday",
  label = "Filter by Day of Week:",
  choices = unique(crashes$WDAY),
  selected = "Monday"
)
```

# Tab 1

## Row

```{r}
# output: leaflet map
leafletOutput(outputId = "map")
```


# Tab 2

## Row

```{r}
# output(s) for tab-2
plotlyOutput(outputId = "plot")
```



```{r}
#| context: server

# assemble leaflet map of crash locations (tab 1)

output$map <- renderLeaflet({

  req(input$coltype)

  filtered <- crashes |>
    filter(
      DATETIME >= input$dates[1],
      DATETIME <= input$dates[2],
      COUNTY == input$county,
      PCF_VIOL_CATEGORY == input$violation,
      TYPE_OF_COLLISION %in% input$coltype
    )

  leafmap <- leaflet(filtered) |>
    addProviderTiles(input$provider)

  if (input$color == "yes") {
    pal <- colorFactor(
    palette = "Reds",   
    domain = filtered$COLLISION_SEVERITY,
    ordered = TRUE
   )
    
    leafmap |>
      addCircles(
        lng = ~POINT_X,
        lat = ~POINT_Y,
        label = ~paste0("Case ID:", CASE_ID, ", ", PCF_VIOL_CATEGORY),
        color = ~pal(COLLISION_SEVERITY),
        weight = 2
      ) |>
      addLegend(
        position = "bottomright",
        pal = pal,
        values = ~COLLISION_SEVERITY,
        title = "Severity"
      )

  } 
  else {

    leafmap |>
      addCircles(
        lng = ~POINT_X,
        lat = ~POINT_Y,
        label = ~paste0("Case ID:", CASE_ID, ", ", PCF_VIOL_CATEGORY),
        weight = 2
      )
  }
})
  


# assemble graphic for tab 2
output$plot <- renderPlotly({
  filtered2 <- crashes |>
    filter((WDAY == input$wday), 
      DATETIME >= input$dates[1],
      DATETIME <= input$dates[2],
      COUNTY == input$county,
      PCF_VIOL_CATEGORY == input$violation,
      TYPE_OF_COLLISION %in% input$coltype) |>
        group_by(TYPE_OF_COLLISION) |>
           summarize(count = n())
g <- filtered2 |> ggplot(aes(y = count, x = TYPE_OF_COLLISION)) +
  geom_col() +
  labs(
    title = "Number and Type of Crashes by Day of Week", 
          x = "Type of Collision", 
          y = "Number of Crashes")
  ggplotly(g)

})

```

